spring.application.name=spring-boot-mongodb

#spring.data.mongodb.uri=mongodb+srv://<username>:<pwd>@cluster0.w5igymh.mongodb.net/students

spring.data.mongodb.uri=mongodb+srv://kaanefeatalay_db_user:5cB9RrMHoMK4hSeg@cluster0.w5igymh.mongodb.net/students